sudo: required
services:
  - docker

before_install:
  - docker build -t vgeorgework/flask .

script:
  - docker run vgeorgework/flask -- --coverage

# after_success:
#   - echo "$DOCKER_PASSWORD" | docekr login -u "$DOCKER_ID" --password-stdin
#   - docker push vgeorgework/flask 
