sudo: required
services:
  - docker

before_install:
  - docker build -t vgeorgework/flask .

script:
  - docker run -d -p 5000:5000 vgeorgework/flask 

# after_success:
#   - echo "$DOCKER_PASSWORD" | docekr login -u "$DOCKER_ID" --password-stdin
#   - docker push vgeorgework/flask 
