apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials-flask
data:
  username: {{ .Values.db.username}}
  password: {{ .Values.db.password}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf-flask
data:
 host: {{ .Values.db.host}}
 name: {{ .Values.db.db_name}}
