apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials-flask
data:
  username: {{ .Values.username}}
  password: {{ .Values.password}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf-flask
data:
 #username: root
 host: {{ .Values.host}}
 name: {{ .Values.name}}
