apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
 username: {{ .Values.db.username}}
 password: {{ .Values.db.password}}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials
data:
 password: {{ .Values.db.rootpassword}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf
data:
 host: {{ .Values.db.host}}
 name: {{ .Values.db.db_name}}

