apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
data:
 username: {{ .Values.username}}
 password: {{ .Values.password}}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials
data:
 password: {{ .Values.rootpassword}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf
data:
 host: mysql
 name: TEST

