apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deploy
  labels:
    app: flask-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
    spec:
      containers:
      - name: flask-web
        image: vgeorgework/flaskapp:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_USER # Setting USER username on mysql From a 'Secret'
          valueFrom:
            secretKeyRef:
              name: db-root-credentials-flask
              key: username
        - name: MYSQL_PASSWORD # Setting USER username on mysql From a 'Secret'
          valueFrom:
            secretKeyRef:
              name: db-root-credentials-flask
              key: password
        - name: MYSQL_DATABASE # Setting Database Name from a 'ConfigMap'
          valueFrom:
            configMapKeyRef:
              name: db-conf-flask
              key: name
        - name: MYSQL_HOST # Setting Database Name from a 'ConfigMap'
          valueFrom:
            configMapKeyRef:
              name: db-conf-flask
              key: host
---
apiVersion: v1
kind: Service
metadata:
  name: flask-web-svc
spec:
  selector:
    app: flask-web
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials-flask
data:
 username: cm9vdAo=
 password: YWRtaW4xMjM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf-flask
data:
 host: mysql
 name: TEST