apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_HOST: mysql
  MYSQL_DB: TEST
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  MYSQL_USER: cm9vdA==
  MYSQL_PASSWORD: dG9vcg==
  MYSQL_ROOT_PASSWORD: dG9vcg==
