apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deploy
  labels:
    app: flask-deploy
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
    spec:
      containers:
      - name: flask-web
        image: vgeorgework/flaskapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Secret
metadata:
  name: db-root-credentials-flask
data:
  #username: cm9vdAo=
  password: YWRtaW4xMjM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-conf-flask
data:
 username: root
 host: mysql
 name: TEST

